"""
PDF and Excel export generation, shared by the team command centre and the
athlete-facing history views. Kept as pure functions (data in, bytes out)
so they're easy to test without touching the database or FastAPI.
"""
import io
from datetime import datetime
from typing import List, Optional

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable

BRAND = colors.HexColor("#10B981")
INK = colors.HexColor("#0B0F17")
MUTED = colors.HexColor("#6B7280")
ROW_ALT = colors.HexColor("#F3F4F6")
RISK_COLORS = {"red": colors.HexColor("#E11D48"), "amber": colors.HexColor("#F59E0B"), "green": colors.HexColor("#10B981")}


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("PfcTitle", parent=ss["Title"], textColor=INK, fontSize=20, spaceAfter=2))
    ss.add(ParagraphStyle("PfcSubtitle", parent=ss["Normal"], textColor=MUTED, fontSize=10, spaceAfter=14))
    ss.add(ParagraphStyle("PfcSection", parent=ss["Heading2"], textColor=INK, fontSize=13, spaceBefore=14, spaceAfter=6))
    return ss


def _header(story, styles, title, subtitle):
    story.append(Paragraph(title, styles["PfcTitle"]))
    story.append(Paragraph(subtitle, styles["PfcSubtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND, spaceAfter=10))


def _table(rows, col_widths, header_bg=INK):
    t = Table(rows, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), header_bg),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
    ]
    t.setStyle(TableStyle(style))
    return t


def _fmt_date(d: str) -> str:
    try:
        return datetime.strptime(d, "%Y-%m-%d").strftime("%d %b %Y")
    except Exception:
        return d


# ---------------------------------------------------------------- team roster PDF
def generate_team_pdf(team_name: str, summary: dict, players: List[dict]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm)
    styles = _styles()
    story = []
    generated = datetime.now().strftime("%d %b %Y, %H:%M")
    _header(story, styles, team_name, f"Squad status report · generated {generated}")

    story.append(Paragraph(
        f"{summary.get('checkedIn', 0)}/{summary.get('total', 0)} checked in today &nbsp;&nbsp;·&nbsp;&nbsp; "
        f"<font color='#E11D48'><b>{summary.get('flagged', 0)} need attention</b></font>",
        styles["Normal"],
    ))

    header_row = ["Player", "Status", "Risk", "Week load", "Monotony", "ACWR", "Readiness"]
    rows = [header_row]
    for p in players:
        if not p.get("joined"):
            rows.append([p["name"], "Not joined", "—", "—", "—", "—", "—"])
            continue
        rows.append([
            p["name"],
            "Checked in" if p.get("checkedInToday") else "Not today",
            (p.get("riskLevel") or "—").capitalize(),
            str(p.get("weekLoad", "—")),
            str(p.get("monotony") if p.get("monotony") is not None else "—"),
            str(p.get("acwr") if p.get("acwr") is not None else "—"),
            f"{p['readinessToday']}/100" if p.get("readinessToday") is not None else "—",
        ])
    story.append(Spacer(1, 6))
    story.append(_table(rows, col_widths=[38 * mm, 24 * mm, 20 * mm, 22 * mm, 22 * mm, 18 * mm, 22 * mm]))

    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "Risk score is a triage aid combining ACWR, monotony, and today's illness/soreness/readiness signals — "
        "not a medical diagnosis. Generated by the Load &amp; Recovery Platform.",
        ParagraphStyle("Foot", parent=styles["Normal"], fontSize=7.5, textColor=MUTED),
    ))
    doc.build(story)
    return buf.getvalue()


def generate_team_excel(team_name: str, players: List[dict]) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Squad"[:31]

    headers = ["Player", "Status", "Risk level", "Risk score", "Avg load", "Peak load", "Week load",
               "Monotony", "Strain", "ACWR", "Readiness today", "Readiness (week avg)"]
    ws.append(headers)
    header_fill = PatternFill(start_color="0B0F17", end_color="0B0F17", fill_type="solid")
    for col in range(1, len(headers) + 1):
        c = ws.cell(row=1, column=col)
        c.font = Font(color="FFFFFF", bold=True)
        c.fill = header_fill
        c.alignment = Alignment(horizontal="center")

    for p in players:
        if not p.get("joined"):
            ws.append([p["name"], "Not joined"] + ["—"] * (len(headers) - 2))
            continue
        ws.append([
            p["name"], "Checked in today" if p.get("checkedInToday") else "Not checked in today",
            (p.get("riskLevel") or "—").capitalize(), p.get("riskScore", "—"),
            p.get("avgLoad", "—"), p.get("peakLoad", "—"), p.get("weekLoad", "—"),
            p.get("monotony", "—"), p.get("strain", "—"), p.get("acwr", "—"),
            p.get("readinessToday", "—"), p.get("readinessWeekAvg", "—"),
        ])

    for col in range(1, len(headers) + 1):
        ws.column_dimensions[get_column_letter(col)].width = 16
    ws.column_dimensions["A"].width = 20
    ws.freeze_panes = "A2"

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------- athlete history PDF
def generate_history_pdf(person_name: str, context_label: str, checkins: List[dict]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm)
    styles = _styles()
    story = []
    generated = datetime.now().strftime("%d %b %Y, %H:%M")
    _header(story, styles, person_name, f"{context_label} · generated {generated}")

    header_row = ["Date", "Sleep", "Hydration", "Motivation", "Soreness", "Illness", "Session load"]
    rows = [header_row]
    for c in sorted(checkins, key=lambda x: x["date"], reverse=True):
        sleep = f"{c['sleepHours']}h · {c['sleepQuality']}/5" if c.get("sleepHours") is not None else f"{c.get('sleepQuality','—')}/5"
        soreness = f"{c.get('sorenessSeverity', 0)}/5" if c.get("sorenessSeverity") else "—"
        illness = "Yes" if c.get("feelingIll") else "—"
        load = str(c["load"]) if c.get("load") else "—"
        rows.append([_fmt_date(c["date"]), sleep, f"{c.get('hydration','—')}/5", f"{c.get('motivation','—')}/5", soreness, illness, load])

    story.append(_table(rows, col_widths=[26 * mm, 28 * mm, 22 * mm, 24 * mm, 22 * mm, 18 * mm, 24 * mm]))
    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "Generated by the Load &amp; Recovery Platform.",
        ParagraphStyle("Foot", parent=styles["Normal"], fontSize=7.5, textColor=MUTED),
    ))
    doc.build(story)
    return buf.getvalue()


# ---------------------------------------------------------------- GPS analysis PDF (optional feature)
def generate_gps_pdf(team_name: str, player_name: str, sessions: List[dict], correlation: Optional[float]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=16 * mm, leftMargin=16 * mm, rightMargin=16 * mm)
    styles = _styles()
    story = []
    generated = datetime.now().strftime("%d %b %Y, %H:%M")
    _header(story, styles, f"{player_name} — GPS load analysis", f"{team_name} · generated {generated}")

    if correlation is not None:
        story.append(Paragraph(
            f"External (GPS) vs. internal (session-RPE) load correlation: <b>{correlation}</b>",
            styles["Normal"],
        ))
    story.append(Spacer(1, 8))

    header_row = ["Date", "Distance (m)", "HSR distance (m)", "Sprints", "Max speed (km/h)", "Session load (internal)"]
    rows = [header_row]
    for s in sorted(sessions, key=lambda x: x["date"], reverse=True):
        rows.append([
            _fmt_date(s["date"]), str(s.get("distance_m", "—")), str(s.get("hsr_distance_m", "—")),
            str(s.get("sprints", "—")), str(s.get("max_speed_kmh", "—")), str(s.get("internal_load", "—")),
        ])
    story.append(_table(rows, col_widths=[24 * mm, 28 * mm, 30 * mm, 20 * mm, 30 * mm, 34 * mm]))
    story.append(Spacer(1, 16))
    story.append(Paragraph(
        "External load (GPS) and internal load (session-RPE = RPE × duration) measure different things — "
        "research shows total distance correlates well with session-RPE, while high-speed running and "
        "accelerations often don't, and that gap is informative, not an error. Generated by the Load &amp; "
        "Recovery Platform.",
        ParagraphStyle("Foot", parent=styles["Normal"], fontSize=7.5, textColor=MUTED),
    ))
    doc.build(story)
    return buf.getvalue()
